### ISSUE TITLE
VertexData description does not specify delta encoding

### ISSUE THREAD

**Issue by nitrologic** [CesiumGS/quantized-mesh#2]
Reading the document in this repos and [here](https://cesiumjs.org/data-and-assets/terrain/formats/quantized-mesh-1.0/) there is no mention of the fact that u, v, and height arrays are both delta and zigzag encoded.

According to the source, it is evident that CesiumTerrainProvider interprets the values as deltas:

```
       var i;
        var u = 0;
        var v = 0;
        var height = 0;

        function zigZagDecode(value) {
            return (value >> 1) ^ (-(value & 1));
        }

        for (i = 0; i < vertexCount; ++i) {
            u += zigZagDecode(uBuffer[i]);
            v += zigZagDecode(vBuffer[i]);
            height += zigZagDecode(heightBuffer[i]);

            uBuffer[i] = u;
            vBuffer[i] = v;
            heightBuffer[i] = height;
        }
```

**Comment by pjcozzi** [comment]
Good eye, thanks @nitrologic!  @tfili could you please make a spec "bug fix?"

**Comment by tfili** [comment]
Thanks @nitrologic. I've opened a PR to update the spec.
